# Generated by Django 5.2.17 on 2026-08-27 20:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.CharField(max_length=9)),
                ('gross_annual_rent_etb', models.DecimalField(decimal_places=2, max_digits=14)),
                ('deduction_etb', models.DecimalField(decimal_places=2, max_digits=14)),
                ('taxable_income_etb', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_due_etb', models.DecimalField(decimal_places=2, max_digits=14)),
                ('effective_rate_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], default='PENDING', max_length=15)),
                ('due_date', models.DateField()),
                ('assessment_pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='contracts.rentalcontract')),
            ],
        ),
    ]
