# Generated by Django 5.2.17 on 2026-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxassessment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], db_index=True, default='PENDING', max_length=15),
        ),
    ]
