# Generated by Django 5.2.17 on 2026-09-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_alter_taxassessment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxassessment',
            name='prn_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
