# Generated by Django 5.2.17 on 2026-09-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0005_srs_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxassessment',
            name='prn_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
