with open('.env', 'a') as f:
    f.write('\nCHAPA_SECRET_KEY=CHASECK_TEST-CVgtazq1KoGsd1fosJKL61XMtyIGDac9\n')
    f.write('AFROMESSAGE_API_KEY=eyJhbGciOiJIUzI1NiJ9.eyJpZGVudGlmaWVyIjoick14RkpTTjg3dHY3VFJVYlhQTHdpU3JaRFNqak1MdnciLCJleHAiOjE3NDcyMzUxNzYsImlhdCI6MTY4OTQ2ODc3NiwianRpIjoiMTQ4NjRkZDQtNTY4MS00M2Y4LThiMWUtMThmYTQ1ZDE1ZGZmIn0.CN7U2-dpnxjZ9-ZWlE8qQ5Yi3Fw6xhpRInkXWL5o-A0\n')
