# Generated by Django 5.2.17 on 2026-09-05 15:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('OTP_DELIVERY', 'OTP Delivery'), ('DEADLINE_WARNING_DAY25', 'Deadline Warning Day 25'), ('DEADLINE_BREACH_DAY30', 'Deadline Breach Day 30'), ('TENANT_REVIEW_REQUEST', 'Tenant Review Request'), ('AUTH_APPROVED', 'Authentication Approved'), ('AUTH_REJECTED', 'Authentication Rejected'), ('TAX_ISSUED', 'Tax Assessment Issued'), ('TAX_REMINDER', 'Tax Payment Reminder'), ('TAX_CONFIRMED', 'Tax Payment Confirmed'), ('DISPUTE_UPDATE', 'Dispute Update'), ('SYSTEM_INFO', 'System Information')], default='SYSTEM_INFO', max_length=30)),
                ('message_amharic', models.TextField(blank=True, default='')),
                ('message_english', models.TextField(blank=True, default='')),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_attempts', models.IntegerField(default=0)),
                ('in_app_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_record_type', models.CharField(blank=True, default='', max_length=50)),
                ('related_record_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
