# Generated by Django 5.2.17 on 2026-08-27 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispute_type', models.CharField(choices=[('UNLAWFUL_RENT_INCREASE', 'Unlawful Rent Increase'), ('ILLEGAL_EVICTION_NOTICE', 'Illegal Eviction Notice'), ('UNREGISTERED_CONTRACT', 'Unregistered Contract'), ('UTILITY_DISCONNECTION', 'Utility Disconnection'), ('DEPOSIT_NOT_RETURNED', 'Deposit Not Returned'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('incident_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('FILED', 'Filed'), ('UNDER_REVIEW', 'Under Review'), ('DECISION_ISSUED', 'Decision Issued'), ('APPEALED', 'Appealed'), ('CLOSED', 'Closed')], default='FILED', max_length=30)),
                ('ruling_text', models.TextField(blank=True, null=True)),
                ('ruling_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_disputes', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.rentalcontract')),
                ('filer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_disputes', to=settings.AUTH_USER_MODEL)),
                ('respondent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_disputes', to=settings.AUTH_USER_MODEL)),
                ('woreda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.woreda')),
            ],
        ),
    ]
