# Generated by Django 5.2.17 on 2026-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('FILED', 'Filed'), ('UNDER_REVIEW', 'Under Review'), ('DECISION_ISSUED', 'Decision Issued'), ('APPEALED', 'Appealed'), ('CLOSED', 'Closed')], db_index=True, default='FILED', max_length=30),
        ),
    ]
