# Generated by Django 5.2.17 on 2026-08-27 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_etb', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('CHAPA_TELEBIRR', 'Chapa Telebirr'), ('CHAPA_CBE', 'Chapa CBE Birr'), ('CHAPA_CARD', 'Chapa Card'), ('PRN_BANK', 'PRN Bank'), ('PRN_TELEBIRR', 'PRN Telebirr'), ('MANUAL', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('prn_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('chapa_tx_ref', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('chapa_checkout_url', models.CharField(blank=True, max_length=500, null=True)),
                ('receipt_pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('clearance_pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tax.taxassessment')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
