# Generated by Django 5.2.17 on 2026-08-27 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('TITLE_DEED', 'Title Deed'), ('HOLDING_CERT', 'Holding Certificate'), ('COURT_ORDER', 'Court Order')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size_bytes', models.IntegerField()),
                ('is_clean', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kebele', models.CharField(blank=True, max_length=50, null=True)),
                ('house_number', models.CharField(max_length=50)),
                ('cadastral_upi', models.CharField(blank=True, max_length=100, null=True)),
                ('building_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('CONDOMINIUM', 'Condominium'), ('TRADITIONAL', 'Traditional'), ('COMMERCIAL_RESIDENTIAL', 'Commercial/Residential')], max_length=30)),
                ('num_rooms', models.IntegerField(null=True)),
                ('floor_area_sqm', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('construction_year', models.IntegerField(null=True)),
                ('num_units', models.IntegerField(default=1)),
                ('monthly_rent_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
