# Generated by Django 5.2.17 on 2026-08-27 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_reg_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('monthly_rent_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_payment_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lease_start_date', models.DateField()),
                ('lease_duration_months', models.IntegerField()),
                ('lease_end_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('TELEBIRR', 'Telebirr'), ('CBE_BIRR', 'CBE Birr')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_TENANT_SIGNATURE', 'Pending Tenant Signature'), ('SIGNED', 'Signed'), ('PENDING_AUTHENTICATION', 'Pending Authentication'), ('REGISTERED', 'Registered'), ('REJECTED', 'Rejected'), ('TERMINATED', 'Terminated')], default='DRAFT', max_length=30)),
                ('signing_date', models.DateTimeField(blank=True, null=True)),
                ('submission_to_woreda_date', models.DateTimeField(blank=True, null=True)),
                ('authenticated_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_registration', models.BooleanField(default=False)),
                ('secure_review_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('secure_review_expires', models.DateTimeField(blank=True, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
