# Generated by Django 5.2.17 on 2026-08-27 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='authenticated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authenticated_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landlord_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='parent_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.rentalcontract'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='properties.property'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
