# Generated by Django 5.2.17 on 2026-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcontract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_TENANT_SIGNATURE', 'Pending Tenant Signature'), ('SIGNED', 'Signed'), ('PENDING_AUTHENTICATION', 'Pending Authentication'), ('REGISTERED', 'Registered'), ('REJECTED', 'Rejected'), ('TERMINATED', 'Terminated')], db_index=True, default='DRAFT', max_length=30),
        ),
    ]
