# Generated by Django 5.2.17 on 2026-08-27 20:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_am', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Woreda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_am', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('sub_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subcity')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('full_name_am', models.CharField(max_length=255)),
                ('full_name_en', models.CharField(max_length=255)),
                ('pin_hash', models.CharField(max_length=255)),
                ('tin', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fayda_id', models.BinaryField(blank=True, null=True)),
                ('role', models.CharField(choices=[('LANDLORD', 'Landlord'), ('TENANT', 'Tenant'), ('WOREDA_OFFICER', 'Woreda Officer'), ('TAX_OFFICER', 'Tax Officer'), ('ADMIN', 'Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('sub_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subcity')),
                ('woreda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.woreda')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
