# Generated by Django 5.2.17 on 2026-09-02 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
