# Generated by Django 5.2.17 on 2026-09-11 08:15

from django.db import migrations, models


def seed_configs(apps, schema_editor):
    SystemConfig = apps.get_model('users', 'SystemConfig')
    configs = [
        {'key': 'LOGIN_MAX_ATTEMPTS', 'value': '5', 'description': 'Number of failed login attempts before lockout'},
        {'key': 'LOGIN_LOCKOUT_DURATION_MINUTES', 'value': '30', 'description': 'Duration of account lockout in minutes'},
    ]
    for conf in configs:
        SystemConfig.objects.get_or_create(key=conf['key'], defaults=conf)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_auditlog_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_config',
            },
        ),
        migrations.RunPython(seed_configs, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='user',
            name='failed_login_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
