# Generated by Django 5.2.17 on 2026-09-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_requires_pin_change_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
